// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.30.0
// source: user_events.proto

package user_events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MessageType ve ServiceType enum'ları
type MessageType int32

const (
	MessageType_UNKNOWN_MESSAGE_TYPE MessageType = 0
	MessageType_USER_CREATED         MessageType = 1
	MessageType_USER_UPDATED         MessageType = 2
	// Diğer mesaj tiplerini buraya ekleyin
	MessageType_AUTH_USER_CREATED MessageType = 3 // Auth için spesifik bir tip
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "UNKNOWN_MESSAGE_TYPE",
		1: "USER_CREATED",
		2: "USER_UPDATED",
		3: "AUTH_USER_CREATED",
	}
	MessageType_value = map[string]int32{
		"UNKNOWN_MESSAGE_TYPE": 0,
		"USER_CREATED":         1,
		"USER_UPDATED":         2,
		"AUTH_USER_CREATED":    3,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_user_events_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_user_events_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_user_events_proto_rawDescGZIP(), []int{0}
}

type ServiceType int32

const (
	ServiceType_UNKNOWN_SERVICE ServiceType = 0
	ServiceType_AUTH_SERVICE    ServiceType = 1
	ServiceType_USER_SERVICE    ServiceType = 2
	ServiceType_CHAT_SERVICE    ServiceType = 3
	ServiceType_RETRY_SERVICE   ServiceType = 4 // Diğer servis tiplerini buraya ekleyin
)

// Enum value maps for ServiceType.
var (
	ServiceType_name = map[int32]string{
		0: "UNKNOWN_SERVICE",
		1: "AUTH_SERVICE",
		2: "USER_SERVICE",
		3: "CHAT_SERVICE",
		4: "RETRY_SERVICE",
	}
	ServiceType_value = map[string]int32{
		"UNKNOWN_SERVICE": 0,
		"AUTH_SERVICE":    1,
		"USER_SERVICE":    2,
		"CHAT_SERVICE":    3,
		"RETRY_SERVICE":   4,
	}
)

func (x ServiceType) Enum() *ServiceType {
	p := new(ServiceType)
	*p = x
	return p
}

func (x ServiceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceType) Descriptor() protoreflect.EnumDescriptor {
	return file_user_events_proto_enumTypes[1].Descriptor()
}

func (ServiceType) Type() protoreflect.EnumType {
	return &file_user_events_proto_enumTypes[1]
}

func (x ServiceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceType.Descriptor instead.
func (ServiceType) EnumDescriptor() ([]byte, []int) {
	return file_user_events_proto_rawDescGZIP(), []int{1}
}

type Message struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type        MessageType            `protobuf:"varint,2,opt,name=type,proto3,enum=user_events.MessageType" json:"type,omitempty"`
	Created     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created,proto3" json:"created,omitempty"`
	FromService ServiceType            `protobuf:"varint,4,opt,name=from_service,json=fromService,proto3,enum=user_events.ServiceType" json:"from_service,omitempty"`
	ToServices  []ServiceType          `protobuf:"varint,5,rep,packed,name=to_services,json=toServices,proto3,enum=user_events.ServiceType" json:"to_services,omitempty"` // Birden fazla hedef servis
	Priority    int32                  `protobuf:"varint,6,opt,name=priority,proto3" json:"priority,omitempty"`
	Headers     map[string]string      `protobuf:"bytes,7,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Headers for metadata
	Critical    bool                   `protobuf:"varint,8,opt,name=critical,proto3" json:"critical,omitempty"`
	RetryCount  int32                  `protobuf:"varint,9,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	// Payload için bir oneof yapısı kullanabiliriz
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*Message_UserCreatedData
	//	*Message_UserUpdatedData
	//	*Message_UserTest
	Payload       isMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_user_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_user_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_user_events_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_UNKNOWN_MESSAGE_TYPE
}

func (x *Message) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *Message) GetFromService() ServiceType {
	if x != nil {
		return x.FromService
	}
	return ServiceType_UNKNOWN_SERVICE
}

func (x *Message) GetToServices() []ServiceType {
	if x != nil {
		return x.ToServices
	}
	return nil
}

func (x *Message) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Message) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Message) GetCritical() bool {
	if x != nil {
		return x.Critical
	}
	return false
}

func (x *Message) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *Message) GetPayload() isMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Message) GetUserCreatedData() *UserCreatedData {
	if x != nil {
		if x, ok := x.Payload.(*Message_UserCreatedData); ok {
			return x.UserCreatedData
		}
	}
	return nil
}

func (x *Message) GetUserUpdatedData() *UserUpdatedData {
	if x != nil {
		if x, ok := x.Payload.(*Message_UserUpdatedData); ok {
			return x.UserUpdatedData
		}
	}
	return nil
}

func (x *Message) GetUserTest() *UserTest {
	if x != nil {
		if x, ok := x.Payload.(*Message_UserTest); ok {
			return x.UserTest
		}
	}
	return nil
}

type isMessage_Payload interface {
	isMessage_Payload()
}

type Message_UserCreatedData struct {
	UserCreatedData *UserCreatedData `protobuf:"bytes,10,opt,name=user_created_data,json=userCreatedData,proto3,oneof"`
}

type Message_UserUpdatedData struct {
	// Diğer olay tipleri için buraya payload'lar eklenecek
	UserUpdatedData *UserUpdatedData `protobuf:"bytes,11,opt,name=user_updated_data,json=userUpdatedData,proto3,oneof"`
}

type Message_UserTest struct {
	UserTest *UserTest `protobuf:"bytes,12,opt,name=user_test,json=userTest,proto3,oneof"`
}

func (*Message_UserCreatedData) isMessage_Payload() {}

func (*Message_UserUpdatedData) isMessage_Payload() {}

func (*Message_UserTest) isMessage_Payload() {}

type UserCreatedData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"` // Diğer ilgili kullanıcı bilgileri
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCreatedData) Reset() {
	*x = UserCreatedData{}
	mi := &file_user_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCreatedData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCreatedData) ProtoMessage() {}

func (x *UserCreatedData) ProtoReflect() protoreflect.Message {
	mi := &file_user_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCreatedData.ProtoReflect.Descriptor instead.
func (*UserCreatedData) Descriptor() ([]byte, []int) {
	return file_user_events_proto_rawDescGZIP(), []int{1}
}

func (x *UserCreatedData) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserCreatedData) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserCreatedData) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type UserUpdatedData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"` // Diğer ilgili kullanıcı bilgileri
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUpdatedData) Reset() {
	*x = UserUpdatedData{}
	mi := &file_user_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUpdatedData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUpdatedData) ProtoMessage() {}

func (x *UserUpdatedData) ProtoReflect() protoreflect.Message {
	mi := &file_user_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUpdatedData.ProtoReflect.Descriptor instead.
func (*UserUpdatedData) Descriptor() ([]byte, []int) {
	return file_user_events_proto_rawDescGZIP(), []int{2}
}

func (x *UserUpdatedData) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserUpdatedData) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserUpdatedData) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type UserTest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserTest) Reset() {
	*x = UserTest{}
	mi := &file_user_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserTest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTest) ProtoMessage() {}

func (x *UserTest) ProtoReflect() protoreflect.Message {
	mi := &file_user_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTest.ProtoReflect.Descriptor instead.
func (*UserTest) Descriptor() ([]byte, []int) {
	return file_user_events_proto_rawDescGZIP(), []int{3}
}

func (x *UserTest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

var File_user_events_proto protoreflect.FileDescriptor

const file_user_events_proto_rawDesc = "" +
	"\n" +
	"\x11user_events.proto\x12\vuser_events\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa0\x05\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\x04type\x18\x02 \x01(\x0e2\x18.user_events.MessageTypeR\x04type\x124\n" +
	"\acreated\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\acreated\x12;\n" +
	"\ffrom_service\x18\x04 \x01(\x0e2\x18.user_events.ServiceTypeR\vfromService\x129\n" +
	"\vto_services\x18\x05 \x03(\x0e2\x18.user_events.ServiceTypeR\n" +
	"toServices\x12\x1a\n" +
	"\bpriority\x18\x06 \x01(\x05R\bpriority\x12;\n" +
	"\aheaders\x18\a \x03(\v2!.user_events.Message.HeadersEntryR\aheaders\x12\x1a\n" +
	"\bcritical\x18\b \x01(\bR\bcritical\x12\x1f\n" +
	"\vretry_count\x18\t \x01(\x05R\n" +
	"retryCount\x12J\n" +
	"\x11user_created_data\x18\n" +
	" \x01(\v2\x1c.user_events.UserCreatedDataH\x00R\x0fuserCreatedData\x12J\n" +
	"\x11user_updated_data\x18\v \x01(\v2\x1c.user_events.UserUpdatedDataH\x00R\x0fuserUpdatedData\x124\n" +
	"\tuser_test\x18\f \x01(\v2\x15.user_events.UserTestH\x00R\buserTest\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\t\n" +
	"\apayload\"\\\n" +
	"\x0fUserCreatedData\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"\\\n" +
	"\x0fUserUpdatedData\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"&\n" +
	"\bUserTest\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername*b\n" +
	"\vMessageType\x12\x18\n" +
	"\x14UNKNOWN_MESSAGE_TYPE\x10\x00\x12\x10\n" +
	"\fUSER_CREATED\x10\x01\x12\x10\n" +
	"\fUSER_UPDATED\x10\x02\x12\x15\n" +
	"\x11AUTH_USER_CREATED\x10\x03*k\n" +
	"\vServiceType\x12\x13\n" +
	"\x0fUNKNOWN_SERVICE\x10\x00\x12\x10\n" +
	"\fAUTH_SERVICE\x10\x01\x12\x10\n" +
	"\fUSER_SERVICE\x10\x02\x12\x10\n" +
	"\fCHAT_SERVICE\x10\x03\x12\x11\n" +
	"\rRETRY_SERVICE\x10\x04B\x0fZ\r./user-eventsb\x06proto3"

var (
	file_user_events_proto_rawDescOnce sync.Once
	file_user_events_proto_rawDescData []byte
)

func file_user_events_proto_rawDescGZIP() []byte {
	file_user_events_proto_rawDescOnce.Do(func() {
		file_user_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_events_proto_rawDesc), len(file_user_events_proto_rawDesc)))
	})
	return file_user_events_proto_rawDescData
}

var file_user_events_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_user_events_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_user_events_proto_goTypes = []any{
	(MessageType)(0),              // 0: user_events.MessageType
	(ServiceType)(0),              // 1: user_events.ServiceType
	(*Message)(nil),               // 2: user_events.Message
	(*UserCreatedData)(nil),       // 3: user_events.UserCreatedData
	(*UserUpdatedData)(nil),       // 4: user_events.UserUpdatedData
	(*UserTest)(nil),              // 5: user_events.UserTest
	nil,                           // 6: user_events.Message.HeadersEntry
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_user_events_proto_depIdxs = []int32{
	0, // 0: user_events.Message.type:type_name -> user_events.MessageType
	7, // 1: user_events.Message.created:type_name -> google.protobuf.Timestamp
	1, // 2: user_events.Message.from_service:type_name -> user_events.ServiceType
	1, // 3: user_events.Message.to_services:type_name -> user_events.ServiceType
	6, // 4: user_events.Message.headers:type_name -> user_events.Message.HeadersEntry
	3, // 5: user_events.Message.user_created_data:type_name -> user_events.UserCreatedData
	4, // 6: user_events.Message.user_updated_data:type_name -> user_events.UserUpdatedData
	5, // 7: user_events.Message.user_test:type_name -> user_events.UserTest
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_user_events_proto_init() }
func file_user_events_proto_init() {
	if File_user_events_proto != nil {
		return
	}
	file_user_events_proto_msgTypes[0].OneofWrappers = []any{
		(*Message_UserCreatedData)(nil),
		(*Message_UserUpdatedData)(nil),
		(*Message_UserTest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_events_proto_rawDesc), len(file_user_events_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_events_proto_goTypes,
		DependencyIndexes: file_user_events_proto_depIdxs,
		EnumInfos:         file_user_events_proto_enumTypes,
		MessageInfos:      file_user_events_proto_msgTypes,
	}.Build()
	File_user_events_proto = out.File
	file_user_events_proto_goTypes = nil
	file_user_events_proto_depIdxs = nil
}
