app:
  name: 'auth-service'
  version: '1.0.0'
  description: 'test'

server:
  port: '8081'
  host: '0.0.0.0'

postgres:
  port: '5432'
  user: 'myuser'
  password: 'mypassword'
  db: 'authdb'
  host: 'localhost'
