app:
  name: 'auth-service'
  version: '1.0.0'
  description: 'test'

server:
  port: 8081
  host: 'localhost'

postgres:
  port: 5432
  user: 'myuser'
  password: 'mypassword'
  db: 'authdb'
  host: 'localhost'
  image:
