app:
  name: 'user-service'
  version: '1.0.0'
  description: 'test'

server:
  port: '8082'
  host: '0.0.0.0'

postgres:
  port: '5432'
  user: 'myuser'
  password: 'mypassword'
  db: 'userdb'
  host: 'localhost'

sessionredis:
  host: 'localhost'
  port: '6379'
  password: ''
  db: 0
